version: '3.7'

services:
  nats:
    image: nats:latest
    ports:
      - 4222:4222
  mongo:
    container_name: mongo_dev
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - dev
  mongo_seed:
    container_name: mongo_seed
    build: .
    networks:
      - dev
    depends_on:
      - mongo
networks:
  dev:
    name: dev
    driver: bridge

