// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sportevent.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sportevent.proto

It has these top-level messages:
	ChatMessage
	Event
	Execution
	Response
	EventFilter
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sport int32

const (
	Sport_BASEBALL   Sport = 0
	Sport_BASKETBALL Sport = 1
	Sport_FOOTBALL   Sport = 2
	Sport_BOXING     Sport = 3
	Sport_GOLF       Sport = 4
	Sport_NASCAR     Sport = 5
	Sport_TENNIS     Sport = 6
)

var Sport_name = map[int32]string{
	0: "BASEBALL",
	1: "BASKETBALL",
	2: "FOOTBALL",
	3: "BOXING",
	4: "GOLF",
	5: "NASCAR",
	6: "TENNIS",
}
var Sport_value = map[string]int32{
	"BASEBALL":   0,
	"BASKETBALL": 1,
	"FOOTBALL":   2,
	"BOXING":     3,
	"GOLF":       4,
	"NASCAR":     5,
	"TENNIS":     6,
}

func (x Sport) String() string {
	return proto.EnumName(Sport_name, int32(x))
}
func (Sport) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ChatMessage struct {
	Email        string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Username     string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Message      string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	CreationDate int64  `protobuf:"varint,4,opt,name=creation_date,json=creationDate" json:"creation_date,omitempty"`
	EventType    string `protobuf:"bytes,5,opt,name=event_type,json=eventType" json:"event_type,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChatMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatMessage) GetCreationDate() int64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *ChatMessage) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

type Event struct {
	Sport        Sport  `protobuf:"varint,1,opt,name=sport,enum=pb.Sport" json:"sport,omitempty"`
	MatchTitle   string `protobuf:"bytes,2,opt,name=match_title,json=matchTitle" json:"match_title,omitempty"`
	DataEvent    string `protobuf:"bytes,3,opt,name=data_event,json=dataEvent" json:"data_event,omitempty"`
	CreationDate int64  `protobuf:"varint,4,opt,name=creation_date,json=creationDate" json:"creation_date,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetSport() Sport {
	if m != nil {
		return m.Sport
	}
	return Sport_BASEBALL
}

func (m *Event) GetMatchTitle() string {
	if m != nil {
		return m.MatchTitle
	}
	return ""
}

func (m *Event) GetDataEvent() string {
	if m != nil {
		return m.DataEvent
	}
	return ""
}

func (m *Event) GetCreationDate() int64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

type Execution struct {
	Symbol         string  `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Market         string  `protobuf:"bytes,2,opt,name=market" json:"market,omitempty"`
	Price          float32 `protobuf:"fixed32,3,opt,name=price" json:"price,omitempty"`
	Quantity       float32 `protobuf:"fixed32,4,opt,name=quantity" json:"quantity,omitempty"`
	ExecutionEpoch int64   `protobuf:"varint,5,opt,name=executionEpoch" json:"executionEpoch,omitempty"`
	StateSymbol    string  `protobuf:"bytes,6,opt,name=stateSymbol" json:"stateSymbol,omitempty"`
}

func (m *Execution) Reset()                    { *m = Execution{} }
func (m *Execution) String() string            { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()               {}
func (*Execution) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Execution) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Execution) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Execution) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Execution) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Execution) GetExecutionEpoch() int64 {
	if m != nil {
		return m.ExecutionEpoch
	}
	return 0
}

func (m *Execution) GetStateSymbol() string {
	if m != nil {
		return m.StateSymbol
	}
	return ""
}

type Response struct {
	IsSuccess bool   `protobuf:"varint,1,opt,name=is_success,json=isSuccess" json:"is_success,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EventFilter struct {
	EventId     string `protobuf:"bytes,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	AggregateId string `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId" json:"aggregate_id,omitempty"`
}

func (m *EventFilter) Reset()                    { *m = EventFilter{} }
func (m *EventFilter) String() string            { return proto.CompactTextString(m) }
func (*EventFilter) ProtoMessage()               {}
func (*EventFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EventFilter) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *EventFilter) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "pb.ChatMessage")
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*Execution)(nil), "pb.Execution")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*EventFilter)(nil), "pb.EventFilter")
	proto.RegisterEnum("pb.Sport", Sport_name, Sport_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SportsEvent service

type SportsEventClient interface {
	// Get all events for the given aggregate and event
	GetEvents(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (*Response, error)
	// Create a new event to the event store
	CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error)
}

type sportsEventClient struct {
	cc *grpc.ClientConn
}

func NewSportsEventClient(cc *grpc.ClientConn) SportsEventClient {
	return &sportsEventClient{cc}
}

func (c *sportsEventClient) GetEvents(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.SportsEvent/GetEvents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sportsEventClient) CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.SportsEvent/CreateEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SportsEvent service

type SportsEventServer interface {
	// Get all events for the given aggregate and event
	GetEvents(context.Context, *EventFilter) (*Response, error)
	// Create a new event to the event store
	CreateEvent(context.Context, *Event) (*Response, error)
}

func RegisterSportsEventServer(s *grpc.Server, srv SportsEventServer) {
	s.RegisterService(&_SportsEvent_serviceDesc, srv)
}

func _SportsEvent_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportsEventServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SportsEvent/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportsEventServer).GetEvents(ctx, req.(*EventFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _SportsEvent_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportsEventServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SportsEvent/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportsEventServer).CreateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _SportsEvent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SportsEvent",
	HandlerType: (*SportsEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _SportsEvent_GetEvents_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _SportsEvent_CreateEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sportevent.proto",
}

func init() { proto.RegisterFile("sportevent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdd, 0x8a, 0xdb, 0x3e,
	0x10, 0xc5, 0xd7, 0xf9, 0x5a, 0x7b, 0x9c, 0x7f, 0xfe, 0x46, 0x94, 0xe2, 0x2e, 0x94, 0x4d, 0x5d,
	0x28, 0xa1, 0x94, 0x5c, 0x6c, 0x1f, 0xa0, 0x24, 0xa9, 0x13, 0xc2, 0xa6, 0x09, 0xd8, 0xb9, 0xe8,
	0x5d, 0x50, 0xec, 0x21, 0x31, 0x8d, 0x3f, 0x2a, 0x29, 0xa5, 0x79, 0x88, 0x3e, 0x42, 0x9f, 0xa3,
	0xaf, 0x57, 0x34, 0xb2, 0xc3, 0xb2, 0x57, 0xbd, 0xf3, 0xf9, 0x8d, 0xa4, 0x39, 0x3a, 0x23, 0x83,
	0x27, 0xab, 0x52, 0x28, 0xfc, 0x81, 0x85, 0x1a, 0x57, 0xa2, 0x54, 0x25, 0x6b, 0x55, 0xfb, 0xe0,
	0xb7, 0x05, 0xee, 0xec, 0xc8, 0xd5, 0x17, 0x94, 0x92, 0x1f, 0x90, 0xbd, 0x80, 0x2e, 0xe6, 0x3c,
	0x3b, 0xf9, 0xd6, 0xd0, 0x1a, 0x39, 0x91, 0x11, 0xec, 0x0e, 0xec, 0xb3, 0x44, 0x51, 0xf0, 0x1c,
	0xfd, 0x16, 0x15, 0xae, 0x9a, 0xf9, 0x70, 0x9b, 0x9b, 0xcd, 0x7e, 0x9b, 0x4a, 0x8d, 0x64, 0x6f,
	0xe1, 0xbf, 0x44, 0x20, 0x57, 0x59, 0x59, 0xec, 0x52, 0xae, 0xd0, 0xef, 0x0c, 0xad, 0x51, 0x3b,
	0xea, 0x37, 0xf0, 0x33, 0x57, 0xc8, 0x5e, 0x03, 0x90, 0xa7, 0x9d, 0xba, 0x54, 0xe8, 0x77, 0xe9,
	0x04, 0x87, 0xc8, 0xf6, 0x52, 0x61, 0xf0, 0xcb, 0x82, 0x6e, 0xa8, 0x15, 0xbb, 0x87, 0x2e, 0xdd,
	0x80, 0x9c, 0x0d, 0x1e, 0x9c, 0x71, 0xb5, 0x1f, 0x13, 0x88, 0x0c, 0x67, 0xf7, 0xe0, 0xe6, 0x5c,
	0x25, 0xc7, 0x9d, 0xca, 0xd4, 0xa9, 0xf1, 0x09, 0x84, 0xb6, 0x9a, 0xe8, 0x56, 0x29, 0x57, 0x7c,
	0x47, 0xa7, 0xd7, 0x66, 0x1d, 0x4d, 0x4c, 0x83, 0x7f, 0xb1, 0x1b, 0xfc, 0xb1, 0xc0, 0x09, 0x7f,
	0x62, 0x72, 0xd6, 0x84, 0xbd, 0x84, 0x9e, 0xbc, 0xe4, 0xfb, 0xb2, 0x89, 0xab, 0x56, 0x9a, 0xe7,
	0x5c, 0x7c, 0x43, 0x55, 0xbb, 0xa8, 0x95, 0x4e, 0xb7, 0x12, 0x59, 0x62, 0x92, 0x6a, 0x45, 0x46,
	0xe8, 0x74, 0xbf, 0x9f, 0x79, 0xa1, 0x32, 0x75, 0xa1, 0x9e, 0xad, 0xe8, 0xaa, 0xd9, 0x3b, 0x18,
	0x60, 0xd3, 0x2e, 0xac, 0xca, 0xe4, 0x48, 0x11, 0xb5, 0xa3, 0x67, 0x94, 0x0d, 0xc1, 0x95, 0x8a,
	0x2b, 0x8c, 0x8d, 0x9d, 0x1e, 0xb5, 0x7d, 0x8a, 0x82, 0x4f, 0x60, 0x47, 0x28, 0xab, 0xb2, 0x90,
	0x94, 0x44, 0x26, 0x77, 0xf2, 0x9c, 0x24, 0x28, 0x25, 0x79, 0xb7, 0x23, 0x27, 0x93, 0xb1, 0x01,
	0xf4, 0x08, 0x84, 0x28, 0x45, 0xed, 0xde, 0x88, 0xe0, 0x11, 0x5c, 0x0a, 0x6a, 0x9e, 0x9d, 0x14,
	0x0a, 0xf6, 0x0a, 0x6c, 0x33, 0xb8, 0x2c, 0xad, 0x6f, 0x7f, 0x4b, 0x7a, 0x99, 0xb2, 0x37, 0xd0,
	0xe7, 0x87, 0x83, 0xc0, 0x03, 0x57, 0xa8, 0xcb, 0xe6, 0x18, 0xf7, 0xca, 0x96, 0xe9, 0x7b, 0x5e,
	0x4f, 0x93, 0xf5, 0xc1, 0x9e, 0x4e, 0xe2, 0x70, 0x3a, 0x59, 0xad, 0xbc, 0x1b, 0x36, 0x00, 0x98,
	0x4e, 0xe2, 0xc7, 0x70, 0x4b, 0xda, 0xd2, 0xd5, 0xf9, 0x66, 0x63, 0x54, 0x8b, 0x01, 0xf4, 0xa6,
	0x9b, 0xaf, 0xcb, 0xf5, 0xc2, 0x6b, 0x33, 0x1b, 0x3a, 0x8b, 0xcd, 0x6a, 0xee, 0x75, 0x34, 0x5d,
	0x4f, 0xe2, 0xd9, 0x24, 0xf2, 0xba, 0xfa, 0x7b, 0x1b, 0xae, 0xd7, 0xcb, 0xd8, 0xeb, 0x3d, 0x20,
	0xb8, 0xb1, 0x6e, 0x21, 0xcd, 0x78, 0x3f, 0x80, 0xb3, 0x40, 0x45, 0xdf, 0x92, 0xfd, 0xaf, 0x5f,
	0xcf, 0x93, 0xdb, 0xdc, 0xf5, 0x35, 0x68, 0xf2, 0x09, 0x6e, 0xd8, 0x08, 0xdc, 0x99, 0x9e, 0x3b,
	0x9a, 0xcd, 0xce, 0x75, 0xfd, 0xf3, 0x95, 0xfb, 0x1e, 0xfd, 0x4c, 0x1f, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0xae, 0x74, 0xf9, 0x60, 0x03, 0x00, 0x00,
}
